### ISSUE TITLE
plt.imshow defaults to antialiasing 

### ISSUE THREAD

**Issue by selasley** [ehu-ai/optical_illusion#1]
Thanks for the interesting notebook.  You should probably use interpolation='none' in your calls to imshow to avoid antialiasing.  See the interpolation section in the [imshow documentation](https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.pyplot.imshow.html)

**Comment by edwhu** [comment]
Thanks for the comment. For some reason, on Google Colab, interpolation='none' gives really bad visual results - the line spacing becomes uneven, even though the line coordinates I generate seem reasonably even. Will investigate this further.
